language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t ravitheja990/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ravitheja990/docker-react npm run test